### ISSUE TITLE
Nothing seems to happen in this repo?

### ISSUE THREAD

**Issue by taddison92** [JulienBreux/rrule-go#1]
As far as I can see, you only define an interface? am I missing something obvious?

**Comment by ghost** [comment]
@taddison92 I believe this library is only for parsing an RRULE string into a struct for easier interaction. I'm sure you'll need to combine this with something else to actually run tasks at those times.

**Comment by alswl** [comment]
Where is the interface implementation?

---

update: https://github.com/teambition/rrule-go works
